### ISSUE TITLE
Can

### ISSUE THREAD

**Issue by OtakuAndFitness** [zivester/node-quickthumb#19]

**Comment by zivester** [comment]
More details appreciated, do you have imagemagick or graphicsmagick  installed?

**Comment by jialbanc** [comment]
Any news about this issue? getting same here.

**Comment by zivester** [comment]
@jialbanc could you provide more details?  Do you have imagemagick or graphicsmagick installed?

**Comment by jialbanc** [comment]
@zivester Yes I installed this one for Windows (ImageMagick-7.0.7-26-Q16-x64-dll.exe) [https://www.imagemagick.org/script/download.php#windows](url), it throws the same error  
```
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: spawn identify ENOENT
    at exports._errnoException (util.js:1023:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

The command magick -version it shows

`
Version: ImageMagick 7.0.7-26 Q16 x64 2018-03-12 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC Modules OpenMP
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg lcms lqr openexr pangocairo png ps raw rsvg tiff webp xml zlib
`

**Comment by zivester** [comment]
Sorry I don't have a windows machine to test this out... my first guess is that the `identify` command is not available with your installed version of imagemagick.  I'm not sure if the library I'm using supports Windows (https://github.com/rsms/node-imagemagick).

I believe the library would need to move to graphiksmagick or a native port of imagemagick (such as https://github.com/elad/node-imagemagick-native) to work on Windows.  Unfortunately I don't have the time at the moment to port the project.

**Comment by Samueleroux** [comment]
The problem come from Imagemagick during the installation there is a button you need to check that tells the script to install "legacy" utilities. 

Just reinstall Imagemagick with this option activated and quickthumb work on windows.

![capture](https://user-images.githubusercontent.com/2677205/39574085-c898c7a8-4ecd-11e8-9db9-c044e2c270f3.PNG)
