### ISSUE TITLE
Not working on windows with installed Imagemagick

### ISSUE THREAD

**Issue by gerbil** [zivester/node-quickthumb#8]
Command:
node make-thumb.js public/images/ /tmp/ 200x200 -p -r

Response:
Converting to 200 x 200

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

**Comment by Phoscur** [comment]
Would be nice if there could be a proper error message if the additional dependency couldn't be loaded. Or just warn and route to the uncompressed image.

**Comment by jeromemiranda** [comment]
Hi @gerbil Can you help me how to set up the PATH that you have mentioned?

**Comment by AamuLumi** [comment]
@jeromemiranda Follow this page and add imagemagick folder path : http://www.computerhope.com/issues/ch000549.htm

**Comment by jklepatch** [comment]
Fixed the issue by uninstalling imagemagick then re-installing it with the option "legacy component" selected. It will include convert.exe, the missing binary in the default install:
http://www.imagemagick.org/discourse-server/viewtopic.php?t=29582
